<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Brizy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>brizy.Message</code>
 */
class Message extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 descriminator = 1;</code>
     */
    protected $descriminator = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $descriminator
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 descriminator = 1;</code>
     * @return int
     */
    public function getDescriminator()
    {
        return $this->descriminator;
    }

    /**
     * Generated from protobuf field <code>int32 descriminator = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDescriminator($var)
    {
        GPBUtil::checkInt32($var);
        $this->descriminator = $var;

        return $this;
    }

}

