<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: doctrine.proto

namespace GPBMetadata;

class Doctrine
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
W
doctrine.protobrizy.message.doctrine"
DoctrineMessage"
DoctrineMessage2bproto3'
        , true);

        static::$is_initialized = true;
    }
}

