<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: doctrine.proto

namespace Brizy\Doctrine;

if (false) {
    /**
     * This class is deprecated. Use Brizy\Doctrine\DoctrineMessage\DoctrineEventType instead.
     * @deprecated
     */
    class DoctrineMessage_DoctrineEventType {}
}
class_exists(DoctrineMessage\DoctrineEventType::class);
@trigger_error('Brizy\Doctrine\DoctrineMessage_DoctrineEventType is deprecated and will be removed in the next major release. Use Brizy\Doctrine\DoctrineMessage\DoctrineEventType instead', E_USER_DEPRECATED);

