name: Generate The Code

on:
  release:
    types: [published]

jobs:
  cancel-previous-workflow:
    name: Cancel previous workflow
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
  build:
    name: Brizy Protobuff Idl
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        php-versions:
          - '7.4'
    steps:
      - name: Checkout Protobuff Idl
        uses: actions/checkout@v2
        with:
          path: protobuf-idl

      - name: Checkout Protogen PHP
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.ACCESS_KEY }}
          repository: bagrinsergiu/brizy-protogen-php
          path: protobuf-php-gen
          fetch-depth: '1'

      - name: Load Evnrorment Data
        uses: falti/dotenv-action@master
        id: env
        with:
          path: protobuf-idl/.env

      - name: Setup protobuf executable
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://github.com/protocolbuffers/protobuf/releases/download/v${{ steps.env.outputs.protobuf_version }}/protoc-${{ steps.env.outputs.protobuf_version }}-linux-x86_64.zip
          unzip -d ./protoc protoc-${{ steps.env.outputs.protobuf_version }}-linux-x86_64.zip
          sudo cp -r protoc/include/google /usr/local/include/
          sudo cp -r protoc/bin/protoc /usr/local/bin
          sudo chmod +x /usr/local/bin/protoc
          rm -rf protoc

          wget https://github.com/ckaznocha/protoc-gen-lint/releases/download/v${{ steps.env.outputs.protobuf_linter_version }}/protoc-gen-lint_linux_amd64.zip
          unzip -d ./protoc-gen-lint protoc-gen-lint_linux_amd64
          sudo cp -r protoc-gen-lint/protoc-gen-lint /usr/local/bin
          sudo chmod +x /usr/local/bin/protoc-gen-lint
          rm -rf ./protoc-gen-lint

      - name: Lint
        run: protoc -I=protobuf-idl/src --lint_out=sort_imports:. protobuf-idl/src/*.proto

      - name: Generate PHP Code
        run: |
          mkdir -p protobuf-php-gen/build
          rm -rf protobuf-php-gen/build/*
          protoc -I=protobuf-idl/src --php_out=protobuf-php-gen/build $(find protobuf-idl/src/ -iname "*.proto")

      - name: Commit generated code
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          cwd: ./protobuf-php-gen
          branch: master
          add: '.'
          message: 'Tag: ${{ github.event.release.tag_name }} Message: ${{github.event.release.body}}'
          tag: ${{ github.event.release.tag_name }}


